Add role assignment public ip & api_server_authorized_ip_ranges
prefapp/tfm pull request #307
Opened 2024-10-16 15:46 UTC by gustavoborragan

2024-10-16 16:35 UTC, gustavoborragan commented
https://github.com/councilbox/claims/pull/797

2024-10-17 10:02 UTC, jcframil requested changes
check commented resource naming

2024-10-17 10:02 UTC, jcframil commented on modules/azure-aks/role_assignment.tf
> +resource "azurerm_role_assignment" "role_assignment_network_contributor_over_public_ip_aks_predev" {
whay named predev?

2024-10-17 10:03 UTC, gustavoborragan commented on modules/azure-aks/role_assignment.tf
> +resource "azurerm_role_assignment" "role_assignment_network_contributor_over_public_ip_aks_predev" {
Changed

2024-10-17 10:14 UTC, merged