Adding cloudamqp-cluster module
prefapp/tfm pull request #379
Opened 2024-12-09 17:31 UTC by JulianGV21

Related to  #370

2024-12-09 17:35 UTC, alambike commented on modules/cloudamqp-cluster/main.tf
> +  count = leght(var.alarms)
leght?

2024-12-09 17:35 UTC, alambike commented on modules/cloudamqp-cluster/main.tf
> +  tags          = [ "terraform" ]
This attributes must be parameterized through variables

2024-12-09 17:35 UTC, alambike commented on modules/cloudamqp-cluster/main.tf
> +}
@JulianGV21 is this a real api key!!!?

2024-12-13 13:56 UTC, alambike commented on modules/cloudamqp-cluster/main.tf
> +}
API Key has been invalidate.

2024-12-17 08:06 UTC, gustavoborragan commented on modules/cloudamqp-cluster/main.tf
> +  count = leght(var.alarms)
It might be more optimal to use a for_each to create resources iteratively https://developer.hashicorp.com/terraform/language/meta-arguments/for_each

2024-12-17 08:07 UTC, gustavoborragan commented on modules/cloudamqp-cluster/main.tf
> +  tags          = [ "terraform" ]
Additionally, you could put a default value if that value will be the most likely.

2024-12-17 08:10 UTC, gustavoborragan commented on modules/cloudamqp-cluster/main.tf
> +}
Yes, please remove that Api Key and generate another one since this repository is public.

2024-12-17 08:12 UTC, gustavoborragan commented on modules/cloudamqp-cluster/notifications.tf
> +resource "cloudamqp_notification" "recipient" {
I think it should be this as in the other cases.

2024-12-17 08:12 UTC, gustavoborragan commented on modules/cloudamqp-cluster/main.tf
> +resource "cloudamqp_instance" "instance" {
I think it should be this as in the other cases.

2024-12-17 08:13 UTC, gustavoborragan commented on modules/cloudamqp-cluster/logs.tf
> +resource "cloudamqp_integration_log" "logs" {
I think it should be this as in the other cases.

2024-12-17 08:19 UTC, gustavoborragan commented on modules/cloudamqp-cluster/README.md
> +## Requirements
Specifically, in the README, I would put links to access important information such as the nomenclature of the instance types or the regions since they are very specific.

https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/guides/info_plan

https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/guides/info_region

In addition, specifically, for each resource, I would put the link to the terraform provider (subject to the version of the same), for example:
- https://registry.terraform.io/providers/cloudamqp/cloudamqp/1.32.1/docs/resources/alarm
- https://github.com/prefapp/tfm/blob/main/modules/azure-vnet-peering/peering.tf#L1

2024-12-17 09:38 UTC, JulianGV21 commented on modules/cloudamqp-cluster/main.tf
> +  tags          = [ "terraform" ]
Will check the default values, the attributes has been parametrized through variables

2024-12-17 09:39 UTC, JulianGV21 commented on modules/cloudamqp-cluster/main.tf
> +  rmq_version   = var.instance_rqm_version
"no_default_alarms = false" has been added

2024-12-17 09:40 UTC, JulianGV21 commented on modules/cloudamqp-cluster/outputs.tf
> +}
Will add missing outputs in the module

2024-12-17 09:40 UTC, JulianGV21 commented on modules/cloudamqp-cluster/notifications.tf
> +resource "cloudamqp_notification" "recipient" {
will be update

2024-12-17 09:40 UTC, JulianGV21 commented on modules/cloudamqp-cluster/main.tf
> +resource "cloudamqp_instance" "instance" {
will be update

2024-12-17 09:40 UTC, JulianGV21 commented on modules/cloudamqp-cluster/logs.tf
> +resource "cloudamqp_integration_log" "logs" {
will be update

2024-12-17 11:15 UTC, JulianGV21 commented on modules/cloudamqp-cluster/main.tf
> +resource "cloudamqp_instance" "instance" {
Shouldn't be better to let the instance as instance instead of this?

2024-12-17 11:20 UTC, JulianGV21 commented on modules/cloudamqp-cluster/terraform.tfvars
> +dcr_id           = "dcr-abc123xyz"
Update: You can add  more than 1 log and metric integration

2024-12-17 16:27 UTC, alambike commented on modules/cloudamqp-cluster/main.tf
> +  rmq_version   = var.instance_rqm_version
mmm, no, I think it should be `no_default_alarms = true` by default, so the default alarms are not generated, and only the alarms defined with this module will be created

2024-12-18 09:47 UTC, JulianGV21 commented on modules/cloudamqp-cluster/main.tf
> +  rmq_version   = var.instance_rqm_version
I wrote it bad here, is set up to true as you say

2024-12-20 13:09 UTC, JulianGV21 commented
Readme.md needs a update for the new atributes and variables

2024-12-30 17:17 UTC, jcframil commented on modules/cloudamqp-cluster/README.md
> +    enviroment = "production" }
```suggestion
      enviroment = "production" }
```

2024-12-30 17:17 UTC, jcframil commented on modules/cloudamqp-cluster/README.md
> +    enviroment = "staging" }
```suggestion
      enviroment = "staging" }
```

2024-12-30 17:20 UTC, JulianGV21 commented on modules/cloudamqp-cluster/README.md
> +    enviroment = "production" }
changed

2024-12-30 17:20 UTC, JulianGV21 commented on modules/cloudamqp-cluster/README.md
> +    enviroment = "staging" }
changed

2024-12-30 17:21 UTC, jcframil commented on modules/cloudamqp-cluster/README.md
> +    license_key = "valid_license_key" }
this is not available in the config parameters: https://registry.terraform.io/providers/cloudamqp/cloudamqp/latest/docs/resources/integration_metric#argument-references

2024-12-30 17:22 UTC, jcframil commented on modules/cloudamqp-cluster/README.md
> +    license_key = "valid_license_key" }
```suggestion
    tags = {
      enviroment = "dev"}
```

2024-12-30 17:28 UTC, jcframil commented on modules/cloudamqp-cluster/logs.tf
> +  tags               = join(",", [for k, v in each.value.tags : "${k}=${v}"])
```suggestion
  region             = var.cloudamqp_instance.region
  tags               = var.cloudamqp_instance.tags
```

2024-12-30 17:29 UTC, jcframil commented on modules/cloudamqp-cluster/metrics.tf
> +  tags              = join(",", [for k, v in each.value.tags : "${k}=${v}"])
```suggestion
  region            = var.cloudamqp_instance.region
  tags              = var.cloudamqp_instance.tags
```

2024-12-30 17:31 UTC, jcframil commented on modules/cloudamqp-cluster/variables.tf
> +    tags                = optional(list(string), [])
```suggestion
    region              = string
    tags                = optional(map(string), {})
```

2024-12-30 17:35 UTC, jcframil commented on modules/cloudamqp-cluster/variables.tf
> +    tags        = ["default", "development"]
```suggestion
    tags        = {}
```

2024-12-30 17:36 UTC, jcframil commented on modules/cloudamqp-cluster/README.md
> +| <a name="input_instance_tags"></a> [instance\_tags](#input_instance_tags) | Tags for the CloudAMQP instance | `list(string)` | `[]` | no |
```suggestion
| <a name="input_instance_tags"></a> [instance\_tags](#input_instance_tags) | Tags for the CloudAMQP instance | `map(string)` | `[]` | no |
```

2024-12-30 17:37 UTC, jcframil commented on modules/cloudamqp-cluster/README.md
> +    license_key = "valid_license_key" }
the example is not in yaml

2024-12-30 17:43 UTC, jcframil requested changes
theres some changes to perform:
- readme example is not in yaml
- i think tags should be `map(string)` and shared between all resources in the same cluster
- region should be treated as tags, shared between all resources in the same cluster
- there's a defined value in the integration metric not present in the provider attributes reference in the readme file, take a look at the comment

2024-12-31 08:18 UTC, JulianGV21 commented on modules/cloudamqp-cluster/README.md
> +    license_key = "valid_license_key" }
license_key is also a tag, not an argument

2024-12-31 08:27 UTC, jcframil commented on modules/cloudamqp-cluster/README.md
> +    license_key = "valid_license_key" }
ok, so we only need to fix indentation
```suggestion
      license_key = "valid_license_key" }
```

2024-12-31 08:31 UTC, JulianGV21 commented on modules/cloudamqp-cluster/README.md
> +    license_key = "valid_license_key" }
Will be fixed

2024-12-31 08:31 UTC, JulianGV21 commented on modules/cloudamqp-cluster/README.md
> +| <a name="input_instance_tags"></a> [instance\_tags](#input_instance_tags) | Tags for the CloudAMQP instance | `list(string)` | `[]` | no |
will change all list values to map in the module

2024-12-31 08:33 UTC, JulianGV21 commented on modules/cloudamqp-cluster/metrics.tf
> +  tags              = join(",", [for k, v in each.value.tags : "${k}=${v}"])
We need join(",", ...) if we want to add more metrics or notifications in the future, because the config that you sugest is only avalible for 1 metric-notification

2024-12-31 09:37 UTC, JulianGV21 commented on modules/cloudamqp-cluster/README.md
> +    license_key = "valid_license_key" }
This is a tfvars data to use the module, shoul be good to have it in the example so future users will only need to change the inputs to try it

2024-12-31 15:56 UTC, alambike commented on modules/cloudamqp-cluster/README.md
> +#Claim
Please, split the examples in 2 code blocks.

2024-12-31 15:56 UTC, alambike commented on modules/cloudamqp-cluster/README.md
> +        source: "./path-to-your-module"
Source attribute can't be used here, in the claims definition

2024-12-31 15:56 UTC, alambike commented on modules/cloudamqp-cluster/README.md
> +
Remove extra empty lines

2024-12-31 15:56 UTC, alambike commented on modules/cloudamqp-cluster/logs.tf
> +  region             = join(",", each.value.region)
join?? Can a cluster be created in multiple regions 🤔?

2024-12-31 16:17 UTC, JulianGV21 commented on modules/cloudamqp-cluster/logs.tf
> +  region             = join(",", each.value.region)
ups

2024-12-31 16:19 UTC, JulianGV21 commented on modules/cloudamqp-cluster/README.md
> +
Done

2024-12-31 16:19 UTC, JulianGV21 commented on modules/cloudamqp-cluster/README.md
> +#Claim
Done

2024-12-31 16:19 UTC, JulianGV21 commented on modules/cloudamqp-cluster/README.md
> +        source: "./path-to-your-module"
Removed

2024-12-31 17:18 UTC, alambike commented on modules/cloudamqp-cluster/logs.tf
> +  tags               = join(",", [for k, v in each.value.tags : "${k}=${v}"])
Mmm, but tags is an list or a map, this expression is for a map isn't it?

2025-01-02 08:19 UTC, JulianGV21 commented on modules/cloudamqp-cluster/logs.tf
> +  tags               = join(",", [for k, v in each.value.tags : "${k}=${v}"])
You can configure logs and metrics tags as a map. The only resource that doesn't have support for tags as a map is the instance.

2025-01-03 15:18 UTC, jcframil commented on modules/cloudamqp-cluster/README.md
> +| <a name="input_firewall_rules"></a> [firewall\_rules](#input\_firewall\_rules) | Firewall rules for the instance | `map(object({ description = string, ip = string, ports = list(string), services =
```suggestion
| <a name="input_firewall_rules"></a> [firewall\_rules](#input\_firewall\_rules) | *Depends on* `enable_firewall=true`.\nFirewall rules for the instance | `map(object({ description = string, ip = string, ports = list(string), services = list(string) }))` | `{}` | no |
```

2025-01-03 15:20 UTC, jcframil approved these changes
lgtm! :+1:

2025-01-03 15:27 UTC, jcframil requested changes
Check the comment on the readme.
The rest seems ok, good job :muscle:

2025-01-03 17:41 UTC, jcframil approved these changes
lgtm

2025-01-07 09:38 UTC, merged