azure aks module
prefapp/tfm pull request #52
Opened 2023-11-22 10:46 UTC by gustavoborragan

2023-11-22 11:06 UTC, jcframil approved these changes
LGTM!

2023-11-22 11:06 UTC, jcframil commented on modules/azure-aks/README.md
> +
this lines should be in example?

2023-11-22 11:39 UTC, jalvarezit commented on modules/azure-aks/README.md
> +module "githuib-oidc" {
```suggestion
module "azure-aks" {
```

2023-11-23 22:57 UTC, alambike requested changes

2023-11-23 22:57 UTC, alambike commented on modules/azure-aks/load_yaml_data.tf
> +  filename = "${path.module}/input.yaml"
Non debe ser un ficheiro yaml, como estaban antes iba bien: https://www.terraform-best-practices.com/naming

2023-11-24 09:45 UTC, closed without merging

2023-11-24 09:45 UTC, gustavoborragan commented
Se cierra a favor de esta PR https://github.com/prefapp/tfm/pull/54